spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudvendor #jdbc:mysql://localhost:3306/cloudvendor?useSSL=false
    username: root
    password:

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none #create-drop #none, update, validate, create

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

#  security:
#    user:
#      name: phat
#      password: 12345

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: caches
      base-path: /actuator2

  endpoint:
    health:
      show-details: always

#  server:
#    port: 8081

#springdoc:
#  show-actuator: true

#server:
#  servlet:
#    context-path: /api

logging:
  level:
    com.example.springrestapi: debug